export default {
    //posts
    FETCH_POSTS_DATA: 'FETCH_POSTS_DATA',
    DELETE_POST: 'DELETE_POST',
    UPDATE_POST: 'UPDATE_POST',
    ADD_POST: 'ADD_POST',

    //users
    FETCH_USERS_DATA: 'FETCH_USERS_DATA',
    DELETE_USER: 'DELETE_USER',
    UPDATE_USER: 'UPDATE_USER',
    ADD_USER: 'ADD_USER',
}